/*
 * 存证溯源接口
 *
 * 尽量通用的存证溯源平台，目前是简单用户体系。
 *
 * API version: 0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SwaggerProof struct {
	// 增量存证依赖的主hash
	Basehash string `json:"basehash,omitempty"`
	// 存证名称
	EvidenceName string `json:"evidenceName,omitempty"`
	// 增量存证前一个hash
	Prehash string `json:"prehash,omitempty"`
	// 区块hash
	ProofBlockHash string `json:"proof_block_hash,omitempty"`
	// 上链时间
	ProofBlockTime int32 `json:"proof_block_time,omitempty"`
	// 存证数据
	ProofData string `json:"proof_data,omitempty"`
	// 删除存证交易hash
	ProofDeleted string `json:"proof_deleted,omitempty"`
	// 删除标志
	ProofDeletedFlag bool `json:"proof_deleted_flag,omitempty"`
	// 删除备注
	ProofDeletedNote string `json:"proof_deleted_note,omitempty"`
	// 存证高度
	ProofHeight int32 `json:"proof_height,omitempty"`
	// 存证高度索引
	ProofHeightIndex int32 `json:"proof_height_index,omitempty"`
	// 存证id
	ProofId string `json:"proof_id,omitempty"`
	// 存证备注
	ProofNote string `json:"proof_note,omitempty"`
	// 组织
	ProofOrganization string `json:"proof_organization,omitempty"`
	// 来源
	ProofOriginal string `json:"proof_original,omitempty"`
	// 存证发起者
	ProofSender string `json:"proof_sender,omitempty"`
	// 交易哈希
	ProofTxHash string `json:"proof_tx_hash,omitempty"`
	// 依赖交易哈希
	SourceHash *interface{} `json:"source_hash,omitempty"`
	// 更新依赖主哈希
	UpdateHash string `json:"update_hash,omitempty"`
	// 更新版本
	UpdateVersion int32 `json:"update_version,omitempty"`
	// 用户认证类型
	UserAuthType int32 `json:"user_auth_type,omitempty"`
	// 用户邮箱
	UserEmail string `json:"user_email,omitempty"`
	// 用户企业名称
	UserEnterpriseName string `json:"user_enterprise_name,omitempty"`
	// 用户头像链接地址
	UserIcon string `json:"user_icon,omitempty"`
	// 用户名
	UserName string `json:"user_name,omitempty"`
	// 用户手机号
	UserPhone string `json:"user_phone,omitempty"`
	// 用户真是名称
	UserRealName string `json:"user_real_name,omitempty"`
	// 存证版本
	Version int32 `json:"version,omitempty"`
}
