/*
 * 存证溯源接口
 *
 * 尽量通用的存证溯源平台，目前是简单用户体系。
 *
 * API version: 0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SwaggerServerResponse struct {
	// 错误描述
	Error_ *interface{} `json:"error,omitempty"`
	// 请求标识
	Id int32 `json:"id,omitempty"`
	// 返回结果
	Result *interface{} `json:"result,omitempty"`
}
