/*
 * 存证溯源接口
 *
 * 尽量通用的存证溯源平台，目前是简单用户体系。
 *
 * API version: 0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SwaggerQRange struct {
	// 小于等于
	End *interface{} `json:"end,omitempty"`
	// 大于
	Gt *interface{} `json:"gt,omitempty"`
	// 字段名
	Key string `json:"key,omitempty"`
	// 小于
	Lt *interface{} `json:"lt,omitempty"`
	// 大于等于
	Start *interface{} `json:"start,omitempty"`
}
