/*
 * 存证溯源接口
 *
 * 尽量通用的存证溯源平台，目前是简单用户体系。
 *
 * API version: 0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ModelProofNoteDetail struct {
	// 增量不用，基础可能要
	Banners []ModelProofBanner `json:"banners,omitempty"`
	// 基础存证的名字
	EvidenceName string `json:"evidenceName,omitempty"`
	// 增量存证的名字
	StepName string `json:"stepName,omitempty"`
	UserIcon string `json:"userIcon,omitempty"`
	UserName string `json:"userName,omitempty"`
	Version int32 `json:"version,omitempty"`
}
